package org.example.hospitalmanagementsystem.entity.type;

public enum SpecializationType {
    GENERAL_PHYSICIAN,
    CARDIOLOGIST,
    DERMATOLOGIST,
    PEDIATRICIAN,
    ORTHOPEDIC,
    GYNECOLOGIST,
    NEUROLOGIST,
    PSYCHIATRIST,
    ENT_SPECIALIST,
    OPHTHALMOLOGIST,
    UROLOGIST,
    ONCOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    PULMONOLOGIST,
    NEPHROLOGIST,
    RADIOLOGIST,
    ANESTHESIOLOGIST,
    PATHOLOGIST,
    SURGEON
}
